### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/warehouse_dataset/models/pallet_free/points.xyz'

### ISSUE THREAD

**Issue by EulerWong** [hoangcuongbk80/Object-RPE#6]
./experiments/scripts/train_warehouse.sh 
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python3 ./tools/train.py --dataset warehouse --dataset_root /warehouse_dataset
/media/euler/Development/DenseFusion/lib/transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
Traceback (most recent call last):
  File "./tools/train.py", line 252, in <module>
    main()
  File "./tools/train.py", line 102, in main
    dataset = PoseDataset_warehouse('train', opt.num_points, True, opt.dataset_root, opt.noise_trans, opt.refine_start)
  File "/media/euler/Development/DenseFusion/datasets/warehouse/dataset.py", line 58, in __init__
  **input_file = open('{0}/models/{1}/points.xyz'.format(self.root, class_input[:-1]))
FileNotFoundError: [Errno 2] No such file or directory: '/warehouse_dataset/models/pallet_free/points.xyz'**

any one meet this problem, i can not find the folder struct in this github.

**Comment by EulerWong** [comment]
sorry, everyone, i fix this problem now, thank you.
i should read the train_warehouse.sh file...
